#
# Module manifest for module 'Az'
#
# Generated by: Microsoft Corporation
#
# Generated on: 2/25/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Az.psm1'

# Version number of this module.
ModuleVersion = '13.3.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd48d710e-85cb-46a1-990f-22dae76f6b5f'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatible with PowerShell and Windows PowerShell.
For more information about the Az module, please visit the following: https://learn.microsoft.com/powershell/azure/'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @(@{ModuleName = 'Az.Accounts'; ModuleVersion = '4.0.2'; }, 
               @{ModuleName = 'Az.Advisor'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Aks'; RequiredVersion = '6.1.0'; }, 
               @{ModuleName = 'Az.AnalysisServices'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.ApiManagement'; RequiredVersion = '4.1.0'; }, 
               @{ModuleName = 'Az.App'; RequiredVersion = '2.0.1'; }, 
               @{ModuleName = 'Az.AppConfiguration'; RequiredVersion = '1.4.0'; }, 
               @{ModuleName = 'Az.ApplicationInsights'; RequiredVersion = '2.3.0'; }, 
               @{ModuleName = 'Az.ArcResourceBridge'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.Attestation'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Automanage'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.Automation'; RequiredVersion = '1.11.1'; }, 
               @{ModuleName = 'Az.Batch'; RequiredVersion = '3.7.0'; }, 
               @{ModuleName = 'Az.Billing'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.Cdn'; RequiredVersion = '3.3.0'; }, 
               @{ModuleName = 'Az.CloudService'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.CognitiveServices'; RequiredVersion = '1.15.0'; }, 
               @{ModuleName = 'Az.Compute'; RequiredVersion = '9.1.0'; }, 
               @{ModuleName = 'Az.ConfidentialLedger'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.ConnectedMachine'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.ContainerInstance'; RequiredVersion = '4.1.1'; }, 
               @{ModuleName = 'Az.ContainerRegistry'; RequiredVersion = '4.3.0'; }, 
               @{ModuleName = 'Az.CosmosDB'; RequiredVersion = '1.17.0'; }, 
               @{ModuleName = 'Az.DataBoxEdge'; RequiredVersion = '1.2.1'; }, 
               @{ModuleName = 'Az.Databricks'; RequiredVersion = '1.10.0'; }, 
               @{ModuleName = 'Az.DataFactory'; RequiredVersion = '1.19.1'; }, 
               @{ModuleName = 'Az.DataLakeAnalytics'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.DataLakeStore'; RequiredVersion = '1.4.0'; }, 
               @{ModuleName = 'Az.DataProtection'; RequiredVersion = '2.6.1'; }, 
               @{ModuleName = 'Az.DataShare'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.DesktopVirtualization'; RequiredVersion = '5.4.1'; }, 
               @{ModuleName = 'Az.DevCenter'; RequiredVersion = '2.0.1'; }, 
               @{ModuleName = 'Az.DevTestLabs'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.Dns'; RequiredVersion = '1.3.1'; }, 
               @{ModuleName = 'Az.DnsResolver'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.ElasticSan'; RequiredVersion = '1.2.1'; }, 
               @{ModuleName = 'Az.EventGrid'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.EventHub'; RequiredVersion = '5.2.0'; }, 
               @{ModuleName = 'Az.FrontDoor'; RequiredVersion = '1.12.0'; }, 
               @{ModuleName = 'Az.Functions'; RequiredVersion = '4.2.0'; }, 
               @{ModuleName = 'Az.HDInsight'; RequiredVersion = '6.3.1'; }, 
               @{ModuleName = 'Az.HealthcareApis'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.HealthDataAIServices'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.IotHub'; RequiredVersion = '2.8.0'; }, 
               @{ModuleName = 'Az.KeyVault'; RequiredVersion = '6.3.1'; }, 
               @{ModuleName = 'Az.Kusto'; RequiredVersion = '2.4.0'; }, 
               @{ModuleName = 'Az.LoadTesting'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.LogicApp'; RequiredVersion = '1.6.0'; }, 
               @{ModuleName = 'Az.MachineLearning'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.MachineLearningServices'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.Maintenance'; RequiredVersion = '1.5.1'; }, 
               @{ModuleName = 'Az.ManagedServiceIdentity'; RequiredVersion = '1.3.0'; }, 
               @{ModuleName = 'Az.ManagedServices'; RequiredVersion = '3.1.0'; }, 
               @{ModuleName = 'Az.MarketplaceOrdering'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Media'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.Migrate'; RequiredVersion = '2.7.0'; }, 
               @{ModuleName = 'Az.Monitor'; RequiredVersion = '6.0.1'; }, 
               @{ModuleName = 'Az.MySql'; RequiredVersion = '1.3.0'; }, 
               @{ModuleName = 'Az.Network'; RequiredVersion = '7.14.0'; }, 
               @{ModuleName = 'Az.NetworkCloud'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.Nginx'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.NotificationHubs'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.OperationalInsights'; RequiredVersion = '3.3.0'; }, 
               @{ModuleName = 'Az.Oracle'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.PolicyInsights'; RequiredVersion = '1.7.1'; }, 
               @{ModuleName = 'Az.PostgreSql'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.PowerBIEmbedded'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.PrivateDns'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.RecoveryServices'; RequiredVersion = '7.5.1'; }, 
               @{ModuleName = 'Az.RedisCache'; RequiredVersion = '1.11.0'; }, 
               @{ModuleName = 'Az.RedisEnterpriseCache'; RequiredVersion = '1.4.1'; }, 
               @{ModuleName = 'Az.Relay'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.ResourceGraph'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.ResourceMover'; RequiredVersion = '1.3.0'; }, 
               @{ModuleName = 'Az.Resources'; RequiredVersion = '7.9.0'; }, 
               @{ModuleName = 'Az.Security'; RequiredVersion = '1.8.0'; }, 
               @{ModuleName = 'Az.SecurityInsights'; RequiredVersion = '3.2.0'; }, 
               @{ModuleName = 'Az.ServiceBus'; RequiredVersion = '4.1.1'; }, 
               @{ModuleName = 'Az.ServiceFabric'; RequiredVersion = '3.5.0'; }, 
               @{ModuleName = 'Az.SignalR'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Sql'; RequiredVersion = '6.0.2'; }, 
               @{ModuleName = 'Az.SqlVirtualMachine'; RequiredVersion = '2.4.0'; }, 
               @{ModuleName = 'Az.StackHCI'; RequiredVersion = '2.5.0'; }, 
               @{ModuleName = 'Az.StackHCIVM'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.Storage'; RequiredVersion = '8.2.0'; }, 
               @{ModuleName = 'Az.StorageMover'; RequiredVersion = '1.5.0'; }, 
               @{ModuleName = 'Az.StorageSync'; RequiredVersion = '2.4.1'; }, 
               @{ModuleName = 'Az.StreamAnalytics'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Support'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Synapse'; RequiredVersion = '3.1.2'; }, 
               @{ModuleName = 'Az.TrafficManager'; RequiredVersion = '1.3.0'; }, 
               @{ModuleName = 'Az.Websites'; RequiredVersion = '3.3.1'; }, 
               @{ModuleName = 'Az.Workloads'; RequiredVersion = '1.0.0'; })

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','ARM','ResourceManager','Linux','AzureAutomationNotSupported'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/azps-license'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '13.3.0 - March 2025
Az.CosmosDB
* Added support for Cosmos DB Table role definition and role assignment related cmdlets.

Az.DataBoxEdge
* Removed ''Microsoft.Azure.Management.DataBoxEdge'' Version ''1.0.0'' PackageReference

Az.DataFactory
* Added more support for Oracle connection properties.
* Added more support for Teradata connection properties.
* Added more support for AzurePostgreSql connection properties.

Az.DataShare
* Removed ''Microsoft.Azure.Management.DataShare'' Version ''1.0.1'' PackageReference

Az.Maintenance
* Migrated SDK generation from autorest csharp to autorest powershell.

Az.Migrate
  * Updated Data.Replication to newer API version
    - Updated Data.Replication to point to stable API version 2024-09-01
  * Rebranded Data.Replication cmdlets
    - Rebranded Data.Replication cmdlets from Azure Stack HCI to Azure Local

Az.PolicyInsights
* Removed ''Microsoft.Azure.Management.PolicyInsights'' Version ''1.0.0'' PackageReference

Az.RecoveryServices
* Updated Restore-AzRecoveryServicesBackupItem to support 0 as a TargetZoneNumber to restore to NoZone.
* Updated Restore-AzRecoveryServicesBackupItem to block cross zonal restore from snapshot RP.

Az.ResourceGraph
* Upgraded API version to 2024-04-01.

Az.Resources
* Added ''-ApplicationId'' as an alias of ''-ServicePrincipalName''.
* Supported getting role assignments at the exact scope via ''-AtScope'' for ''Get-AzRoleAssignment''. 

Az.ServiceBus
* Fixed a bug when invoke ''Set-AzServiceBusNamespace'' with parameter ''NoWait'' [#26998]

Az.Sql
* Fixed GitHub issue #12417 ''Get-AzSqlElasticPoolDatabase doesn''t enumerate output.''
    - fixed the output to enumerate the results.

Az.Storage
* Supported new SkuName when create/update Storage account for Files Provisioned v2 account type:  ''StandardV2_LRS'', ''StandardV2_GRS'', ''StandardV2_ZRS'', ''StandardV2_GZRS'', ''PremiumV2_LRS'', ''PremiumV2_ZRS''
    - ''New-AzStorageAccount''
    - ''Set-AzStorageAccount''
* Supported Get File Service Usage on Files Provisioned v2 account type.
    - ''Get-AzStorageFileServiceUsage''
* Supported create/update file share on new parameters on Files Provisioned v2 account type with new parameter: ''-ProvisionedBandwidthMibps'', ''-ProvisionedIops''''
    - ''New-AzRmStorageShare''
    - ''Update-AzRmStorageShare''
* Supported create/update/Get file share on new parameters on Files Provisioned v1 account type with new parameter: ''-PaidBurstingEnabled'', ''-PaidBurstingMaxBandwidthMibps'', ''-PaidBurstingMaxIops''
    - ''New-AzRmStorageShare''
    - ''Update-AzRmStorageShare''
    - ''Get-AzStorageFileServiceUsage''
* Supported get file share new properties for Files Provisioned v1/v2 account type
    - ''Get-AzStorageFileServiceUsage''

Az.Synapse
* Updated Azure.Analytics.Synapse.Artifacts to 1.0.0-preview.21.

Az.Websites
* Migrated Websites.Helper generation from autorest csharp to autorest powershell.

Az.Workloads
* General availability for module Az.Workloads
* Upgraded API version to 2024-09-01
'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoUgYJKoZIhvcNAQcCoIIoQzCCKD8CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDdXXUc5t4HlDI2
# Pti3137lzOFe61xozCZL6VQ3s6uZ1KCCDYUwggYDMIID66ADAgECAhMzAAAEA73V
# lV0POxitAAAAAAQDMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTEzWhcNMjUwOTExMjAxMTEzWjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQCfdGddwIOnbRYUyg03O3iz19XXZPmuhEmW/5uyEN+8mgxl+HJGeLGBR8YButGV
# LVK38RxcVcPYyFGQXcKcxgih4w4y4zJi3GvawLYHlsNExQwz+v0jgY/aejBS2EJY
# oUhLVE+UzRihV8ooxoftsmKLb2xb7BoFS6UAo3Zz4afnOdqI7FGoi7g4vx/0MIdi
# kwTn5N56TdIv3mwfkZCFmrsKpN0zR8HD8WYsvH3xKkG7u/xdqmhPPqMmnI2jOFw/
# /n2aL8W7i1Pasja8PnRXH/QaVH0M1nanL+LI9TsMb/enWfXOW65Gne5cqMN9Uofv
# ENtdwwEmJ3bZrcI9u4LZAkujAgMBAAGjggGCMIIBfjAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU6m4qAkpz4641iK2irF8eWsSBcBkw
# VAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMwMDEyKzUwMjkyNjAfBgNVHSMEGDAW
# gBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIw
# MTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDEx
# XzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIB
# AFFo/6E4LX51IqFuoKvUsi80QytGI5ASQ9zsPpBa0z78hutiJd6w154JkcIx/f7r
# EBK4NhD4DIFNfRiVdI7EacEs7OAS6QHF7Nt+eFRNOTtgHb9PExRy4EI/jnMwzQJV
# NokTxu2WgHr/fBsWs6G9AcIgvHjWNN3qRSrhsgEdqHc0bRDUf8UILAdEZOMBvKLC
# rmf+kJPEvPldgK7hFO/L9kmcVe67BnKejDKO73Sa56AJOhM7CkeATrJFxO9GLXos
# oKvrwBvynxAg18W+pagTAkJefzneuWSmniTurPCUE2JnvW7DalvONDOtG01sIVAB
# +ahO2wcUPa2Zm9AiDVBWTMz9XUoKMcvngi2oqbsDLhbK+pYrRUgRpNt0y1sxZsXO
# raGRF8lM2cWvtEkV5UL+TQM1ppv5unDHkW8JS+QnfPbB8dZVRyRmMQ4aY/tx5x5+
# sX6semJ//FbiclSMxSI+zINu1jYerdUwuCi+P6p7SmQmClhDM+6Q+btE2FtpsU0W
# +r6RdYFf/P+nK6j2otl9Nvr3tWLu+WXmz8MGM+18ynJ+lYbSmFWcAj7SYziAfT0s
# IwlQRFkyC71tsIZUhBHtxPliGUu362lIO0Lpe0DOrg8lspnEWOkHnCT5JEnWCbzu
# iVt8RX1IV07uIveNZuOBWLVCzWJjEGa+HhaEtavjy6i7MIIHejCCBWKgAwIBAgIK
# YQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlm
# aWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
# OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYD
# VQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+la
# UKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc
# 6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4D
# dato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+
# lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
# kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6
# A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmd
# X4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
# 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zd
# sGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3
# T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS
# 4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRI
# bmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBD
# uRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jv
# c29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1h
# cnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkA
# YwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn
# 8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7
# v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0b
# pdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/
# KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvy
# CInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
# mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJi
# hsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYb
# BL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
# oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sL
# gOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtX
# cVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCGiMwghofAgEBMIGVMH4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
# Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAAQDvdWVXQ87GK0AAAAA
# BAMwDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIEuX
# FT2UWLxwues6+U9APVK8rzG6J+MgAHjXKinW3wIxMEIGCisGAQQBgjcCAQwxNDAy
# oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20wDQYJKoZIhvcNAQEBBQAEggEAi7k9cRk9b+m/AgywFhaa/cJrvtWRAswZWiiL
# yJvd4v3kuXHF9+mSEf+Os3wpDCZzyM/FKkj2gEA62DauqdF8YbYcndshCDu1+UgV
# G6XjxM/GkRqf0JrQI9myZDXb+HhUbxmI73VybE3qZk6wS0+ce3HIIb8e8ACY+2z7
# XgDdZahf2VVhQB+/cDsaflCqoxVB+mkbUsB3EJWFDIduQ5dbyF0ri4HV3Oc/b0E2
# 0sk3m2miSjz1MORMvXEFDeh4QsPPyX5UU3QVoxDKPb1q3bdiliUibOdMQeEIA9g2
# Y1XuCYsIy5iQ41j9z8smYj9FRmuMFAdWWoS1Ke0hnwPoPrTD3KGCF60wghepBgor
# BgEEAYI3AwMBMYIXmTCCF5UGCSqGSIb3DQEHAqCCF4YwgheCAgEDMQ8wDQYJYIZI
# AWUDBAIBBQAwggFaBgsqhkiG9w0BCRABBKCCAUkEggFFMIIBQQIBAQYKKwYBBAGE
# WQoDATAxMA0GCWCGSAFlAwQCAQUABCBJWaiAvIhkm0gfAQN33V6uobPnOSHe2WAO
# PGC85I8LDQIGZ7Y0ZNJrGBMyMDI1MDIyNTA3MjExNS43NTlaMASAAgH0oIHZpIHW
# MIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQL
# EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsT
# Hm5TaGllbGQgVFNTIEVTTjoyQTFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
# b2Z0IFRpbWUtU3RhbXAgU2VydmljZaCCEfswggcoMIIFEKADAgECAhMzAAAB+R9n
# jXWrpPGxAAEAAAH5MA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFBDQSAyMDEwMB4XDTI0MDcyNTE4MzEwOVoXDTI1MTAyMjE4MzEwOVowgdMxCzAJ
# BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jv
# c29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVs
# ZCBUU1MgRVNOOjJBMUEtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
# ZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
# tD1MH3yAHWHNVslC+CBTj/Mpd55LDPtQrhN7WeqFhReC9xKXSjobW1ZHzHU8V2BO
# JUiYg7fDJ2AxGVGyovUtgGZg2+GauFKk3ZjjsLSsqehYIsUQrgX+r/VATaW8/ONW
# y6lOyGZwZpxfV2EX4qAh6mb2hadAuvdbRl1QK1tfBlR3fdeCBQG+ybz9JFZ45LN2
# ps8Nc1xr41N8Qi3KVJLYX0ibEbAkksR4bbszCzvY+vdSrjWyKAjR6YgYhaBaDxE2
# KDJ2sQRFFF/egCxKgogdF3VIJoCE/Wuy9MuEgypea1Hei7lFGvdLQZH5Jo2QR5uN
# 8hiMc8Z47RRJuIWCOeyIJ1YnRiiibpUZ72+wpv8LTov0yH6C5HR/D8+AT4vqtP57
# ITXsD9DPOob8tjtsefPcQJebUNiqyfyTL5j5/J+2d+GPCcXEYoeWZ+nrsZSfrd5D
# HM4ovCmD3lifgYnzjOry4ghQT/cvmdHwFr6yJGphW/HG8GQd+cB4w7wGpOhHVJby
# 44kGVK8MzY9s32Dy1THnJg8p7y1sEGz/A1y84Zt6gIsITYaccHhBKp4cOVNrfoRV
# Ux2G/0Tr7Dk3fpCU8u+5olqPPwKgZs57jl+lOrRVsX1AYEmAnyCyGrqRAzpGXyk1
# HvNIBpSNNuTBQk7FBvu+Ypi6A7S2V2Tj6lzYWVBvuGECAwEAAaOCAUkwggFFMB0G
# A1UdDgQWBBSJ7aO6nJXJI9eijzS5QkR2RlngADAfBgNVHSMEGDAWgBSfpxVdAF5i
# XYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
# c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
# JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRw
# Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRp
# bWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1Ud
# JQEB/wQMMAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsF
# AAOCAgEAZiAJgFbkf7jfhx/mmZlnGZrpae+HGpxWxs8I79vUb8GQou50M1ns7iwG
# 2CcdoXaq7VgpVkNf1uvIhrGYpKCBXQ+SaJ2O0BvwuJR7UsgTaKN0j/yf3fpHD0kt
# H+EkEuGXs9DBLyt71iutVkwow9iQmSk4oIK8S8ArNGpSOzeuu9TdJjBjsasmuJ+2
# q5TjmrgEKyPe3TApAio8cdw/b1cBAmjtI7tpNYV5PyRI3K1NhuDgfEj5kynGF/ui
# zP1NuHSxF/V1ks/2tCEoriicM4k1PJTTA0TCjNbkpmBcsAMlxTzBnWsqnBCt9d+U
# d9Va3Iw9Bs4ccrkgBjLtg3vYGYar615ofYtU+dup+LuU0d2wBDEG1nhSWHaO+u2y
# 6Si3AaNINt/pOMKU6l4AW0uDWUH39OHH3EqFHtTssZXaDOjtyRgbqMGmkf8KI3qI
# VBZJ2XQpnhEuRbh+AgpmRn/a410Dk7VtPg2uC422WLC8H8IVk/FeoiSS4vFodhnc
# FetJ0ZK36wxAa3FiPgBebRWyVtZ763qDDzxDb0mB6HL9HEfTbN+4oHCkZa1HKl8B
# 0s8RiFBMf/W7+O7EPZ+wMH8wdkjZ7SbsddtdRgRARqR8IFPWurQ+sn7ftEifaojz
# uCEahSAcq86yjwQeTPN9YG9b34RTurnkpD+wPGTB1WccMpsLlM0wggdxMIIFWaAD
# AgECAhMzAAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYD
# VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
# MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3Nv
# ZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIy
# MjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5
# vQ7VgtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64
# NmeFRiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhu
# je3XD9gmU3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl
# 3GoPz130/o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPg
# yY9+tVSP3PoFVZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I
# 5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2
# ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/
# TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy
# 16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
# 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
# XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMB
# AAEwIwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQW
# BBSfpxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30B
# ATBBMD8GCCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L0RvY3MvUmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYB
# BAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMB
# Af8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBL
# oEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMv
# TWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggr
# BgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
# b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
# reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27
# DzHkwo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pv
# vinLbtg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9Ak
# vUCgvxm2EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWK
# NsIdw2FzLixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2
# kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+
# c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep
# 8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+Dvk
# txW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1Zyvg
# DbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
# 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDVjCCAj4CAQEwggEBoYHZpIHW
# MIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQL
# EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsT
# Hm5TaGllbGQgVFNTIEVTTjoyQTFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
# b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsOAwIaAxUAqs5WjWO7zVAK
# mIcdwhqgZvyp6UaggYMwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAx
# MDANBgkqhkiG9w0BAQsFAAIFAOtnSfswIhgPMjAyNTAyMjQxOTQxNDdaGA8yMDI1
# MDIyNTE5NDE0N1owdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA62dJ+wIBADAHAgEA
# AgIb/DAHAgEAAgIT8DAKAgUA62ibewIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgor
# BgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBCwUA
# A4IBAQCBWOMotcV2lF/1i2p2lbekIX9r1wytt1Gxmd+t91RWatnB6Lz6n2M7BDa7
# d2AV/cDTBwydiW6g5cxJQOghcyI+0iH8SCiuMXmma2TVfQT0gTvOm0Ti1ZeHFiP0
# 9Vizyp9amj+ey8AvJ+O4V491Il13a2DYdDpudO3Sg3U3r54wIb7IRheZnP/9KkGr
# IbXBI1SczfImkb9uxoD2LeIq/DbyDEg7969YadM3R8UGEr8Y+PZJ0wJ/NB2pWJGa
# GhvvhY5km/KHzpkbjWaYXoRqTGh1fV9KdERd2vyqzTI6D6c1mXPSHp08ltkPyDOS
# A6/aVN/SGMxA78HYu3Xr9T2l2h7yMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTACEzMAAAH5H2eNdauk8bEAAQAAAfkwDQYJYIZIAWUD
# BAIBBQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0B
# CQQxIgQg+vdsVYnbDvSAWw3xDSvj3TG9VjlkbosemKfJmXr2zRYwgfoGCyqGSIb3
# DQEJEAIvMYHqMIHnMIHkMIG9BCA5I4zIHvCN+2T66RUOLCZrUEVdoKlKl8VeCO5S
# bGLYEDCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB
# +R9njXWrpPGxAAEAAAH5MCIEIP5wgmwhcuu9P/fJ+uPRk2wfg3nn/qKlVEwf/Ec7
# vud/MA0GCSqGSIb3DQEBCwUABIICAAuI/zAYziuZ4ZD57jhS2X9az2hNrQjyc4mJ
# okbwtEULDC3Kij7tpqQUE1mO9eLzCQ/Zc+iXY+n4Fny/1tc4kjpFEqhQWpPRRNHj
# slMLFMRUQphOv8Th9DhMhgWMJHjrRLUZkbuCfDJGm848wb1dAsdZuaEi53jNI9sW
# L8tdPfwAyTUL4sKohIQK9zuMKWodZc73Mhlqbb/HH9GU3ygL+lLpYl7NF+3ejjYu
# BgJYEq6HoHOmzUlXC/YGsvjqe57NEfY2dBdcchfJ/pPbUiLt5NlXoRIA0xEOsC/l
# 2CoDeAHm0bHmiIU1a5xiH9MhVSluaEUWwRilG21Wk/qU6UsUqKJCRPFBNA8pLYGC
# i4nq09ILR48XuZxPrsD3dTLdZ0LgsuzNVgSQ3NdZ+wF5PcwK3aZSb3YDDkJGwxJG
# 0XJ4Xy3zOW+lIFO67KKy5XnCsfDCq5qY5QyFmJq5a02ERRNFIZHfKPz+XUYl4vNa
# kmVDQYnQEuiWnqiQUSpB4TxdCJ6MN65uA5W/hDicYqgojG7DKAv5k8PV5GWBLU2q
# IOcYqPJzrjxYxkdq0LEqduUlTtJHsGZSBTLpvrIg1A9HZr7+iIDqoDbDnihPWUc7
# vVtZ2lY0toRJFuFdZVeiEwOxRmtWZkCYmwNWPdaJCj0Y946F4tl82/+D61IePNHf
# eflpn7fq
# SIG # End signature block
