apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-storage-claim
  namespace: wg-easy
spec:
  accessModes:
  - ReadWriteOnce
  # - ReadWriteMany
  storageClassName: managed-csi # local-storage-zfs
  volumeName: wg-easy-pv
  resources:
    requests:
      storage: 128Gi # 256Mi